# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/ECE/Desktop/LSTM_IOT_SEC/softmax/softmax.srcs/sources_1/ip/SRAM_512x4096_2/SRAM_512x4096.xci
# IP: The module: 'SRAM_512x4096' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/ECE/Desktop/LSTM_IOT_SEC/softmax/softmax.srcs/sources_1/ip/SRAM_512x4096_2/SRAM_512x4096_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'SRAM_512x4096'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: c:/Users/ECE/Desktop/LSTM_IOT_SEC/softmax/softmax.srcs/sources_1/ip/SRAM_512x4096_2/SRAM_512x4096.xci
# IP: The module: 'SRAM_512x4096' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/ECE/Desktop/LSTM_IOT_SEC/softmax/softmax.srcs/sources_1/ip/SRAM_512x4096_2/SRAM_512x4096_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'SRAM_512x4096'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
