# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
create_project -in_memory -part xa7a12tcpg238-2I

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Users/ECE/Desktop/LSTM_IOT_SEC/test/test.cache/wt [current_project]
set_property parent.project_path C:/Users/ECE/Desktop/LSTM_IOT_SEC/test/test.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_cache_permissions disable [current_project]
read_verilog -library xil_defaultlib {
  C:/Users/ECE/Desktop/LSTM_IOT_SEC/src/area_LSTM_cell/SRAM_128x2048.v
  C:/Users/ECE/Desktop/LSTM_IOT_SEC/src/area_LSTM_cell/SRAM_16x512.v
  C:/Users/ECE/Desktop/LSTM_IOT_SEC/src/area_LSTM_cell/inpdt.v
  C:/Users/ECE/Desktop/LSTM_IOT_SEC/src/area_LSTM_cell/sigmoid_LUT.v
  C:/Users/ECE/Desktop/LSTM_IOT_SEC/src/area_LSTM_cell/tanh_LUT.v
  C:/Users/ECE/Desktop/LSTM_IOT_SEC/src/area_LSTM_cell/lstm_5.5_SUN.v
}
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top LSTM -part xa7a12tcpg238-2I


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef LSTM.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file LSTM_utilization_synth.rpt -pb LSTM_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
