# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/User/Desktop/LSTM_IOT_SEC/project_1/project_1.srcs/sources_1/ip/SRAM_128x2048/SRAM_128x2048.xci
# IP: The module: 'SRAM_128x2048' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/User/Desktop/LSTM_IOT_SEC/project_1/project_1.srcs/sources_1/ip/SRAM_128x2048/SRAM_128x2048_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'SRAM_128x2048'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: c:/Users/User/Desktop/LSTM_IOT_SEC/project_1/project_1.srcs/sources_1/ip/SRAM_128x2048/SRAM_128x2048.xci
# IP: The module: 'SRAM_128x2048' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/User/Desktop/LSTM_IOT_SEC/project_1/project_1.srcs/sources_1/ip/SRAM_128x2048/SRAM_128x2048_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'SRAM_128x2048'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
