# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/ECE/project_1/project_1.srcs/sources_1/ip/BRAM_16x512_1/BRAM_16x512.xci
# IP: The module: 'BRAM_16x512' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/ECE/project_1/project_1.srcs/sources_1/ip/BRAM_16x512_1/BRAM_16x512_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'BRAM_16x512'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: c:/Users/ECE/project_1/project_1.srcs/sources_1/ip/BRAM_16x512_1/BRAM_16x512.xci
# IP: The module: 'BRAM_16x512' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/ECE/project_1/project_1.srcs/sources_1/ip/BRAM_16x512_1/BRAM_16x512_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'BRAM_16x512'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
